//! Peer transport: async TCP listener + outbound dialer with reconnection.
//!
//! A `Peer` is a cheap, cloneable handle to the shared node state. All clones
//! refer to the same document, broadcast channel and peer counter. Spawn one
//! task per capability:
//!
//! ```text
//! let peer = Peer::new(id);
//! tokio::spawn({ let p = peer.clone(); async move { p.listen(port).await } });
//! tokio::spawn({ let p = peer.clone(); async move { p.connect(addr).await } });
//! // … drive with peer.local_op() / peer.text() from the CLI task.
//! ```

use std::sync::{
    atomic::{AtomicU64, AtomicUsize, Ordering},
    Arc,
};
use std::time::Duration;

use anyhow::Result;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::{broadcast, Mutex};
use tokio::time::sleep;
use tracing::{info, warn};

use crate::crdt::sequence::{Op, Rga};
use crate::network::protocol::Message;
use crate::PeerId;

const CHAN_CAP: usize = 256;
const BACKOFF_BASE_MS: u64 = 200;
const BACKOFF_MAX_MS: u64 = 30_000;

/// A single peer/replica. Clone freely — all copies share the same document.
#[derive(Clone)]
pub struct Peer {
    /// This replica's stable identifier.
    pub peer_id: PeerId,
    doc: Arc<Mutex<Rga>>,
    /// Monotonically increasing sequence number for ops generated by this peer.
    seq: Arc<AtomicU64>,
    /// Sending here fans a message out to every active peer-writer task.
    broadcast_tx: broadcast::Sender<Message>,
    peers_count: Arc<AtomicUsize>,
}

impl Peer {
    pub fn new(peer_id: PeerId) -> Self {
        let (broadcast_tx, _) = broadcast::channel(CHAN_CAP);
        Peer {
            peer_id,
            doc: Arc::new(Mutex::new(Rga::new())),
            seq: Arc::new(AtomicU64::new(0)),
            broadcast_tx,
            peers_count: Arc::new(AtomicUsize::new(0)),
        }
    }

    // ── networking ────────────────────────────────────────────────────────────

    /// Accept incoming peer connections. Runs until the task is cancelled.
    pub async fn listen(&self, port: u16) -> Result<()> {
        let listener = TcpListener::bind(format!("0.0.0.0:{port}")).await?;
        info!(peer_id = self.peer_id, "listening on 0.0.0.0:{port}");
        loop {
            let (stream, addr) = listener.accept().await?;
            info!(peer_id = self.peer_id, "accepted {addr}");
            let peer = self.clone();
            tokio::spawn(async move {
                peer.peers_count.fetch_add(1, Ordering::Relaxed);
                if let Err(e) = peer.run_connection(stream).await {
                    warn!("connection {addr} closed: {e}");
                }
                peer.peers_count.fetch_sub(1, Ordering::Relaxed);
            });
        }
    }

    /// Connect to a remote peer, retrying with exponential backoff on failure.
    /// Runs until the task is cancelled — never returns in normal operation.
    pub async fn connect(&self, addr: String) {
        let mut backoff = BACKOFF_BASE_MS;
        loop {
            match TcpStream::connect(&addr).await {
                Ok(stream) => {
                    info!(peer_id = self.peer_id, "connected to {addr}");
                    backoff = BACKOFF_BASE_MS;
                    self.peers_count.fetch_add(1, Ordering::Relaxed);
                    if let Err(e) = self.run_connection(stream).await {
                        warn!("{addr} disconnected: {e}");
                    }
                    self.peers_count.fetch_sub(1, Ordering::Relaxed);
                }
                Err(e) => warn!("cannot reach {addr}: {e}; retry in {backoff}ms"),
            }
            sleep(Duration::from_millis(backoff)).await;
            backoff = (backoff * 2).min(BACKOFF_MAX_MS);
        }
    }

    // ── document API ──────────────────────────────────────────────────────────

    /// Apply an op generated locally, then broadcast it to all connected peers.
    pub async fn local_op(&self, op: Op) -> Result<()> {
        let seq = self.seq.fetch_add(1, Ordering::Relaxed);
        self.doc.lock().await.apply(&op);
        // Ignore send errors: no connected peers yet is fine.
        let _ = self.broadcast_tx.send(Message::Op {
            from: self.peer_id,
            seq,
            op,
        });
        Ok(())
    }

    /// Apply a message received from a remote peer.
    /// Does NOT re-broadcast — callers are responsible for fan-out topology.
    pub async fn remote_op(&self, msg: Message) {
        match msg {
            Message::Op { op, .. } => self.doc.lock().await.apply(&op),
            Message::Sync { ops, .. } => {
                let mut doc = self.doc.lock().await;
                for op in ops {
                    doc.apply(&op);
                }
            }
            Message::Hello { peer_id } => info!("hello from peer {peer_id}"),
        }
    }

    /// Current document text (tombstoned characters excluded).
    pub async fn text(&self) -> String {
        self.doc.lock().await.text()
    }

    /// Number of currently open peer connections.
    pub fn peers_connected(&self) -> usize {
        self.peers_count.load(Ordering::Relaxed)
    }

    // ── internal ──────────────────────────────────────────────────────────────

    async fn run_connection(&self, stream: TcpStream) -> Result<()> {
        let (r, mut w) = tokio::io::split(stream);
        let mut lines = BufReader::new(r).lines();
        // Subscribe before the hello so we don't miss ops applied between
        // accepting the connection and entering the select loop.
        let mut rx = self.broadcast_tx.subscribe();

        let hello = serde_json::to_string(&Message::Hello { peer_id: self.peer_id })? + "\n";
        w.write_all(hello.as_bytes()).await?;

        loop {
            tokio::select! {
                // Inbound: a message from the remote peer.
                line = lines.next_line() => {
                    match line? {
                        None => break, // remote closed the connection
                        Some(s) => match serde_json::from_str::<Message>(&s) {
                            Ok(msg) => self.remote_op(msg).await,
                            Err(e) => warn!("parse error ({e}): {s}"),
                        },
                    }
                }
                // Outbound: a local op to forward to this peer.
                msg = rx.recv() => {
                    match msg {
                        Ok(m) => {
                            let line = serde_json::to_string(&m)? + "\n";
                            w.write_all(line.as_bytes()).await?;
                        }
                        Err(broadcast::error::RecvError::Lagged(n)) => {
                            warn!("broadcast lagged by {n} messages");
                        }
                        Err(broadcast::error::RecvError::Closed) => break,
                    }
                }
            }
        }
        Ok(())
    }
}

// ── unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crdt::sequence::{Char, Id};

    fn ins(peer_id: u64, counter: u64, ch: char) -> Op {
        Op::Insert {
            after: None,
            ch: Char {
                id: Id { peer_id, counter },
                value: ch,
                deleted: false,
            },
        }
    }

    #[tokio::test]
    async fn local_op_updates_text() {
        let p = Peer::new(1);
        p.local_op(ins(1, 1, 'a')).await.unwrap();
        assert_eq!(p.text().await, "a");
    }

    #[tokio::test]
    async fn remote_op_updates_text() {
        let p = Peer::new(1);
        p.remote_op(Message::Op {
            from: 2,
            seq: 0,
            op: ins(2, 1, 'b'),
        })
        .await;
        assert_eq!(p.text().await, "b");
    }

    #[tokio::test]
    async fn remote_op_is_idempotent() {
        let p = Peer::new(1);
        let msg = Message::Op {
            from: 2,
            seq: 0,
            op: ins(2, 1, 'x'),
        };
        p.remote_op(msg.clone()).await;
        p.remote_op(msg).await;
        assert_eq!(p.text().await, "x");
    }

    #[tokio::test]
    async fn peers_connected_starts_at_zero() {
        assert_eq!(Peer::new(1).peers_connected(), 0);
    }

    #[tokio::test]
    async fn two_peers_exchange_ops_over_loopback() {
        let p1 = Peer::new(1);
        let p2 = Peer::new(2);

        // Bind p1 to an ephemeral port.
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();

        // Spawn p1's accept loop (single-shot: accept one connection then drop).
        let p1_srv = p1.clone();
        tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            p1_srv.peers_count.fetch_add(1, Ordering::Relaxed);
            let _ = p1_srv.run_connection(stream).await;
            p1_srv.peers_count.fetch_sub(1, Ordering::Relaxed);
        });

        // p2 dials p1.
        let stream = TcpStream::connect(format!("127.0.0.1:{port}"))
            .await
            .unwrap();
        let p2_conn = p2.clone();
        tokio::spawn(async move {
            let _ = p2_conn.run_connection(stream).await;
        });

        // Give the handshake time to complete.
        sleep(Duration::from_millis(50)).await;

        // p1 applies a local op — it should reach p2.
        p1.local_op(ins(1, 1, 'h')).await.unwrap();
        sleep(Duration::from_millis(50)).await;

        assert_eq!(p2.text().await, "h");
    }
}
