//! Peer transport: async TCP listener + outbound dialer with reconnection.
//!
//! A `Peer` is a cheap, cloneable handle to the shared node state. All clones
//! refer to the same document, broadcast channel and peer counter. Spawn one
//! task per capability:
//!
//! ```text
//! let peer = Peer::new(id);
//! tokio::spawn({ let p = peer.clone(); async move { p.listen(port).await } });
//! tokio::spawn({ let p = peer.clone(); async move { p.connect(addr).await } });
//! // … drive with peer.local_op() / peer.text() from the CLI task.
//! ```

use std::sync::{
    atomic::{AtomicU64, AtomicUsize, Ordering},
    Arc,
};
use std::time::Duration;

use anyhow::Result;
use tokio::io::{AsyncBufReadExt, AsyncWriteExt, BufReader};
use tokio::net::{TcpListener, TcpStream};
use tokio::sync::{broadcast, Mutex};
use tokio::time::sleep;
use tracing::{info, warn};

use crate::crdt::gcounter::GCounter;
use crate::crdt::sequence::{ApplyResult, Char, Id, Op, Rga};
use crate::network::protocol::Message;
use crate::storage::persistence::OpLog;
use crate::PeerId;

const CHAN_CAP: usize = 256;
const BACKOFF_BASE_MS: u64 = 200;
const BACKOFF_MAX_MS: u64 = 30_000;

type OpBatch = Vec<(PeerId, Op)>;

/// Apply `candidates` to `doc` with multi-pass retry for missing anchors.
/// Returns `(applied, still_pending)` — no async, no side effects.
fn apply_candidates(doc: &mut Rga, mut candidates: OpBatch) -> (OpBatch, OpBatch) {
    let mut applied = Vec::new();
    loop {
        let before = candidates.len();
        let mut retry = Vec::new();
        for (pid, op) in candidates.drain(..) {
            match doc.apply(&op) {
                ApplyResult::Applied => applied.push((pid, op)),
                ApplyResult::MissingAnchor => retry.push((pid, op)),
                ApplyResult::Duplicate => {}
            }
        }
        candidates = retry;
        if candidates.is_empty() || candidates.len() == before {
            break;
        }
    }
    (applied, candidates)
}

/// Document state protected by a single mutex so that applying ops and
/// managing the pending queue are always atomic with respect to each other.
/// This eliminates the race where a concurrent task drains the queue between
/// another task's apply and its post-apply drain.
struct DocState {
    doc: Rga,
    /// Live ops whose anchor/target has not yet arrived; retried on every
    /// successful apply so they are never permanently dropped.
    pending: Vec<(PeerId, Op)>,
}

/// A single peer/replica. Clone freely — all copies share the same document.
#[derive(Clone)]
pub struct Peer {
    /// This replica's stable identifier.
    pub peer_id: PeerId,
    doc_state: Arc<Mutex<DocState>>,
    /// Monotonically increasing sequence number for ops generated by this peer.
    seq: Arc<AtomicU64>,
    /// Sending here fans a message out to every active peer-writer task.
    broadcast_tx: broadcast::Sender<Message>,
    peers_count: Arc<AtomicUsize>,
    /// Optional persistence log. When set, every applied op is appended.
    log: Arc<Mutex<Option<OpLog>>>,
    /// Monotonic counter for generating unique local Op Ids (separate from the
    /// wire sequence number so callers can create ops before calling local_op).
    id_seq: Arc<AtomicU64>,
    /// Emits the full document text after every applied op; browser clients subscribe.
    ui_tx: broadcast::Sender<String>,
    /// Tracks how many ops each peer has contributed, using a G-Counter.
    op_counter: Arc<Mutex<GCounter>>,
}

impl Peer {
    pub fn new(peer_id: PeerId) -> Self {
        let (broadcast_tx, _) = broadcast::channel(CHAN_CAP);
        let (ui_tx, _) = broadcast::channel(CHAN_CAP);
        Peer {
            peer_id,
            doc_state: Arc::new(Mutex::new(DocState {
                doc: Rga::new(),
                pending: Vec::new(),
            })),
            seq: Arc::new(AtomicU64::new(0)),
            broadcast_tx,
            peers_count: Arc::new(AtomicUsize::new(0)),
            log: Arc::new(Mutex::new(None)),
            id_seq: Arc::new(AtomicU64::new(1)),
            ui_tx,
            op_counter: Arc::new(Mutex::new(GCounter::new())),
        }
    }

    /// Attach a persistence log. All subsequent ops (local and remote) are appended.
    pub async fn set_log(&self, log: OpLog) {
        *self.log.lock().await = Some(log);
    }

    /// Truncate the op-log to zero bytes so the next run starts with an empty
    /// document. Not called automatically — wire to a CLI command or shutdown
    /// hook if a reset capability is needed.
    pub async fn clear_log(&self) {
        if let Some(log) = self.log.lock().await.as_mut() {
            if let Err(e) = log.clear().await {
                warn!("failed to clear op-log on shutdown: {e}");
            }
        }
    }

    /// Apply ops loaded from disk at startup — no broadcasting, no re-logging.
    ///
    /// Also advances `id_seq` past every counter this peer used in previous
    /// sessions so that new ops never collide with replayed ids (which would
    /// cause `Rga::apply` to silently discard them as duplicates).
    pub async fn replay_ops(&self, ops: Vec<Op>) {
        // Scan for the max counter before applying so id_seq is advanced
        // correctly even for ops that turn out to be unresolvable.
        let mut max_counter = 0u64;
        for op in &ops {
            let (op_peer, op_counter) = match op {
                Op::Insert { ch, .. } => (ch.id.peer_id, ch.id.counter),
                Op::Delete { target } => (target.peer_id, target.counter),
            };
            if op_peer == self.peer_id && op_counter > max_counter {
                max_counter = op_counter;
            }
        }
        {
            let mut state = self.doc_state.lock().await;
            // Multi-pass apply handles out-of-order entries in the log (can
            // happen when concurrent tasks write dependent ops close together).
            let candidates: OpBatch = ops.into_iter().map(|op| (0, op)).collect();
            let (_, still_pending) = apply_candidates(&mut state.doc, candidates);
            if !still_pending.is_empty() {
                warn!(
                    "{} op(s) unresolvable during replay — log may be incomplete",
                    still_pending.len()
                );
            }
        }
        if max_counter >= self.id_seq.load(Ordering::Relaxed) {
            self.id_seq.store(max_counter + 1, Ordering::Relaxed);
            tracing::info!(
                peer_id = self.peer_id,
                id_seq = max_counter + 1,
                "id_seq advanced past replayed ops",
            );
        }
    }

    /// Subscribe to document-state notifications for the browser UI.
    /// Each message is the full document text after an op was applied.
    pub fn subscribe_ui(&self) -> broadcast::Receiver<String> {
        self.ui_tx.subscribe()
    }

    /// Insert `ch` at visible text offset `visible_offset` (0 = prepend).
    pub async fn browser_insert(&self, visible_offset: usize, ch: char) -> Result<()> {
        let after = {
            let state = self.doc_state.lock().await;
            if visible_offset == 0 {
                None
            } else {
                state.doc.id_at_visible(visible_offset - 1)
            }
        };
        let counter = self.id_seq.fetch_add(1, Ordering::Relaxed);
        let op = Op::Insert {
            after,
            ch: Char {
                id: Id {
                    peer_id: self.peer_id,
                    counter,
                },
                value: ch,
                deleted: false,
            },
        };
        self.local_op(op).await
    }

    /// Delete the visible character at `visible_offset`.
    pub async fn browser_delete(&self, visible_offset: usize) -> Result<()> {
        let target = self
            .doc_state
            .lock()
            .await
            .doc
            .id_at_visible(visible_offset);
        tracing::debug!(
            op_type = "delete",
            pos = visible_offset,
            target_peer = target.map(|id| id.peer_id),
            target_counter = target.map(|id| id.counter),
            "ws_intent_resolved",
        );
        if let Some(target) = target {
            self.local_op(Op::Delete { target }).await?;
        }
        Ok(())
    }

    // ── networking ────────────────────────────────────────────────────────────

    /// Accept incoming peer connections. Runs until the task is cancelled.
    pub async fn listen(&self, port: u16) -> Result<()> {
        let listener = TcpListener::bind(format!("0.0.0.0:{port}")).await?;
        info!(peer_id = self.peer_id, "listening on 0.0.0.0:{port}");
        loop {
            let (stream, addr) = listener.accept().await?;
            info!(peer_id = self.peer_id, "accepted {addr}");
            let peer = self.clone();
            tokio::spawn(async move {
                peer.peers_count.fetch_add(1, Ordering::Relaxed);
                if let Err(e) = peer.run_connection(stream).await {
                    warn!("connection {addr} closed: {e}");
                }
                peer.peers_count.fetch_sub(1, Ordering::Relaxed);
            });
        }
    }

    /// Connect to a remote peer, retrying with exponential backoff on failure.
    /// Runs until the task is cancelled — never returns in normal operation.
    pub async fn connect(&self, addr: String) {
        let mut backoff = BACKOFF_BASE_MS;
        loop {
            match TcpStream::connect(&addr).await {
                Ok(stream) => {
                    info!(peer_id = self.peer_id, "connected to {addr}");
                    backoff = BACKOFF_BASE_MS;
                    self.peers_count.fetch_add(1, Ordering::Relaxed);
                    if let Err(e) = self.run_connection(stream).await {
                        warn!("{addr} disconnected: {e}");
                    }
                    self.peers_count.fetch_sub(1, Ordering::Relaxed);
                }
                Err(e) => warn!("cannot reach {addr}: {e}; retry in {backoff}ms"),
            }
            sleep(Duration::from_millis(backoff)).await;
            backoff = (backoff * 2).min(BACKOFF_MAX_MS);
        }
    }

    // ── document API ──────────────────────────────────────────────────────────

    /// Apply an op generated locally, persist it, then broadcast to all peers.
    pub async fn local_op(&self, op: Op) -> Result<()> {
        let seq = self.seq.fetch_add(1, Ordering::Relaxed);
        let text = {
            let mut state = self.doc_state.lock().await;
            state.doc.apply(&op);
            state.doc.text()
        };
        self.op_counter.lock().await.increment(self.peer_id, 1);
        if let Some(log) = self.log.lock().await.as_mut() {
            log.append(&op).await?;
        }
        let _ = self.ui_tx.send(text);
        // Ignore send errors: no connected peers yet is fine.
        let _ = self.broadcast_tx.send(Message::Op {
            from: self.peer_id,
            seq,
            op,
        });
        Ok(())
    }

    /// Apply a message received from a remote peer, persisting ops if a log is set.
    /// Does NOT re-broadcast — callers are responsible for fan-out topology.
    pub async fn remote_op(&self, msg: Message) {
        match msg {
            Message::Op { ref op, from, seq } => {
                tracing::debug!(from, seq, ?op, "remote_op_received");

                // Push the new op onto the pending queue and immediately try to
                // drain everything — all under one lock so no concurrent task can
                // slip in between the apply and the post-apply drain.
                let (applied, text) = {
                    let mut state = self.doc_state.lock().await;
                    state.pending.push((from, op.clone()));
                    let candidates = std::mem::take(&mut state.pending);
                    let (applied, still_pending) = apply_candidates(&mut state.doc, candidates);
                    if !still_pending.is_empty() {
                        warn!("{} op(s) buffered awaiting anchor", still_pending.len());
                    }
                    state.pending = still_pending;
                    let text = state.doc.text();
                    (applied, text)
                };

                {
                    let mut counter = self.op_counter.lock().await;
                    for (pid, _) in &applied {
                        counter.increment(*pid, 1);
                    }
                }
                tracing::debug!(
                    text_len = text.len(),
                    applied = applied.len(),
                    "remote_op_applied"
                );
                if let Some(log) = self.log.lock().await.as_mut() {
                    for (_, applied_op) in &applied {
                        if let Err(e) = log.append(applied_op).await {
                            warn!("op-log write failed: {e}");
                            break;
                        }
                    }
                }
                let _ = self.ui_tx.send(text);
            }
            Message::Sync { ops, .. } => {
                // Track which ops are genuinely new so we only log those.
                let mut applied_indices: Vec<usize> = Vec::new();
                let (drain_applied, text) = {
                    let mut state = self.doc_state.lock().await;
                    // Multi-pass: retry ops whose anchor/target hasn't arrived yet.
                    // Each pass applies at least one op (progress), so this terminates
                    // in at most O(n) passes for n dependent ops in the batch.
                    let mut pending: Vec<usize> = (0..ops.len()).collect();
                    loop {
                        let before = pending.len();
                        let mut retry = Vec::new();
                        for &idx in &pending {
                            match state.doc.apply(&ops[idx]) {
                                ApplyResult::MissingAnchor => retry.push(idx),
                                ApplyResult::Duplicate => {}
                                ApplyResult::Applied => applied_indices.push(idx),
                            }
                        }
                        pending = retry;
                        if pending.is_empty() || pending.len() == before {
                            if !pending.is_empty() {
                                // Feed into the pending queue — anchors may
                                // arrive from another peer after this Sync.
                                let to_buffer: OpBatch = pending
                                    .iter()
                                    .map(|&idx| {
                                        let pid = match &ops[idx] {
                                            Op::Insert { ch, .. } => ch.id.peer_id,
                                            Op::Delete { target } => target.peer_id,
                                        };
                                        (pid, ops[idx].clone())
                                    })
                                    .collect();
                                warn!("{} sync op(s) buffered awaiting anchor", to_buffer.len());
                                state.pending.extend(to_buffer);
                            }
                            break;
                        }
                    }
                    // Drain live ops that were buffered waiting for an anchor that
                    // may have just arrived in this Sync batch — same lock, no race.
                    let candidates = std::mem::take(&mut state.pending);
                    let (drain_applied, still_pending) =
                        apply_candidates(&mut state.doc, candidates);
                    if !still_pending.is_empty() {
                        state.pending = still_pending;
                    }
                    let text = state.doc.text();
                    (drain_applied, text)
                };
                // Advance id_seq past any ops this peer generated in a previous
                // session that arrived via Sync. Without this, fresh inserts
                // collide with those old IDs and are silently discarded as
                // duplicates until the counter naturally surpasses the old max.
                {
                    let current = self.id_seq.load(Ordering::Relaxed);
                    let max_own = ops
                        .iter()
                        .filter_map(|op| match op {
                            Op::Insert { ch, .. } if ch.id.peer_id == self.peer_id => {
                                Some(ch.id.counter)
                            }
                            Op::Delete { target } if target.peer_id == self.peer_id => {
                                Some(target.counter)
                            }
                            _ => None,
                        })
                        .max();
                    if let Some(max) = max_own {
                        let needed = max + 1;
                        if needed > current {
                            self.id_seq.store(needed, Ordering::Relaxed);
                            tracing::info!(
                                peer_id = self.peer_id,
                                id_seq = needed,
                                "id_seq advanced after sync",
                            );
                        }
                    }
                }
                // G-Counter: count sync ops + any ops freed from the pending queue.
                {
                    let mut counter = self.op_counter.lock().await;
                    for &idx in &applied_indices {
                        let pid = match &ops[idx] {
                            Op::Insert { ch, .. } => ch.id.peer_id,
                            Op::Delete { target } => target.peer_id,
                        };
                        counter.increment(pid, 1);
                    }
                    for (pid, _) in &drain_applied {
                        counter.increment(*pid, 1);
                    }
                }
                // Only log ops that were newly applied — duplicates are already on disk.
                if let Some(log) = self.log.lock().await.as_mut() {
                    for &idx in &applied_indices {
                        if let Err(e) = log.append(&ops[idx]).await {
                            warn!("op-log write failed during sync: {e}");
                            break;
                        }
                    }
                    for (_, applied_op) in &drain_applied {
                        if let Err(e) = log.append(applied_op).await {
                            warn!("op-log write failed (pending drain): {e}");
                            break;
                        }
                    }
                }
                let _ = self.ui_tx.send(text);
            }
            Message::Hello { peer_id } => info!("hello from peer {peer_id}"),
            // State frames are browser-only; peers never send them.
            Message::State { .. } => {}
        }
    }

    /// Current document text (tombstoned characters excluded).
    pub async fn text(&self) -> String {
        self.doc_state.lock().await.doc.text()
    }

    /// Number of currently open peer connections.
    pub fn peers_connected(&self) -> usize {
        self.peers_count.load(Ordering::Relaxed)
    }

    /// Per-peer op counts tracked by the G-Counter, sorted by peer id.
    pub async fn op_counts(&self) -> Vec<(u64, u64)> {
        self.op_counter.lock().await.counts()
    }

    // ── internal ──────────────────────────────────────────────────────────────

    async fn run_connection(&self, stream: TcpStream) -> Result<()> {
        let (r, mut w) = tokio::io::split(stream);
        let mut lines = BufReader::new(r).lines();
        // Subscribe before the hello so we don't miss ops applied between
        // accepting the connection and entering the select loop.
        let mut rx = self.broadcast_tx.subscribe();

        let hello = serde_json::to_string(&Message::Hello {
            peer_id: self.peer_id,
        })? + "\n";
        w.write_all(hello.as_bytes()).await?;

        // Send a catch-up Sync so the remote peer sees all ops we've applied.
        // The lock is released before the async disk read to avoid holding it
        // across an await point.
        let log_path = self.log.lock().await.as_ref().map(|l| l.path().to_owned());
        if let Some(path) = log_path {
            let ops = OpLog::load(&path).await.unwrap_or_default();
            if !ops.is_empty() {
                let sync = serde_json::to_string(&Message::Sync {
                    from: self.peer_id,
                    ops,
                })? + "\n";
                w.write_all(sync.as_bytes()).await?;
            }
        }

        loop {
            tokio::select! {
                // Inbound: a message from the remote peer.
                line = lines.next_line() => {
                    match line? {
                        None => break, // remote closed the connection
                        Some(s) => match serde_json::from_str::<Message>(&s) {
                            Ok(msg) => self.remote_op(msg).await,
                            Err(e) => warn!("parse error ({e}): {s}"),
                        },
                    }
                }
                // Outbound: a local op to forward to this peer.
                msg = rx.recv() => {
                    match msg {
                        Ok(m) => {
                            let line = serde_json::to_string(&m)? + "\n";
                            w.write_all(line.as_bytes()).await?;
                        }
                        Err(broadcast::error::RecvError::Lagged(n)) => {
                            warn!("broadcast lagged by {n} messages; dropping connection to force re-sync");
                            break;
                        }
                        Err(broadcast::error::RecvError::Closed) => break,
                    }
                }
            }
        }
        Ok(())
    }
}

// ── unit tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crdt::sequence::{Char, Id};

    fn ins(peer_id: u64, counter: u64, ch: char) -> Op {
        Op::Insert {
            after: None,
            ch: Char {
                id: Id { peer_id, counter },
                value: ch,
                deleted: false,
            },
        }
    }

    #[tokio::test]
    async fn local_op_updates_text() {
        let p = Peer::new(1);
        p.local_op(ins(1, 1, 'a')).await.unwrap();
        assert_eq!(p.text().await, "a");
    }

    #[tokio::test]
    async fn remote_op_updates_text() {
        let p = Peer::new(1);
        p.remote_op(Message::Op {
            from: 2,
            seq: 0,
            op: ins(2, 1, 'b'),
        })
        .await;
        assert_eq!(p.text().await, "b");
    }

    #[tokio::test]
    async fn remote_op_is_idempotent() {
        let p = Peer::new(1);
        let msg = Message::Op {
            from: 2,
            seq: 0,
            op: ins(2, 1, 'x'),
        };
        p.remote_op(msg.clone()).await;
        p.remote_op(msg).await;
        assert_eq!(p.text().await, "x");
    }

    #[tokio::test]
    async fn peers_connected_starts_at_zero() {
        assert_eq!(Peer::new(1).peers_connected(), 0);
    }

    #[tokio::test]
    async fn two_peers_exchange_ops_over_loopback() {
        let p1 = Peer::new(1);
        let p2 = Peer::new(2);

        // Bind p1 to an ephemeral port.
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let port = listener.local_addr().unwrap().port();

        // Spawn p1's accept loop (single-shot: accept one connection then drop).
        let p1_srv = p1.clone();
        tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            p1_srv.peers_count.fetch_add(1, Ordering::Relaxed);
            let _ = p1_srv.run_connection(stream).await;
            p1_srv.peers_count.fetch_sub(1, Ordering::Relaxed);
        });

        // p2 dials p1.
        let stream = TcpStream::connect(format!("127.0.0.1:{port}"))
            .await
            .unwrap();
        let p2_conn = p2.clone();
        tokio::spawn(async move {
            let _ = p2_conn.run_connection(stream).await;
        });

        // Give the handshake time to complete.
        sleep(Duration::from_millis(50)).await;

        // p1 applies a local op — it should reach p2.
        p1.local_op(ins(1, 1, 'h')).await.unwrap();
        sleep(Duration::from_millis(50)).await;

        assert_eq!(p2.text().await, "h");
    }
}
